package HelloApp;


/**
* HelloApp/HelloOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Hello.idl
* Tuesday, 22 April, 2025 2:45:44 AM IST
*/

public interface HelloOperations 
{
  String sayHello ();
} // interface HelloOperations
